name: Fetch Tosca Access Token and Execute Tests
 
on:
  push:
#  schedule:
#    - cron: '30 14 * * *'
 
jobs:
  fetch_and_execute_tests:
    runs-on: ubuntu-latest
 
    steps:
      - name: Request Tosca Execution API Access Token
        id: get_token
        run: |
          response=$(curl --location --request POST 'https://server.tosca.azure.cloud.bmw/tua/connect/token' \
            --header 'Content-Type: application/x-www-form-urlencoded' \
            --data-urlencode 'grant_type=client_credentials' \
            --data-urlencode 'client_id=dXIkAoN7-UCAdHanf1ReWA' \
            --data-urlencode 'client_secret=JpwhDQeHyU6HAsfBf59PLQ_Berx-f4IUyF8uefh7bgAQ')
          
          echo "Raw Response: $response"
 
          token=$(echo $response | jq -r '.access_token')
 
          echo "Access Token: $token"
 
          echo "TOKEN=$token" >> $GITHUB_ENV
 
      - name: Trigger Tosca Test Execution
        run: |
          curl --location --request POST 'https://server.tosca.azure.cloud.bmw/automationobjectservice/api/Execution/enqueue' \
            --header 'Content-Type: application/json' \
            --header 'X-Tricentis: OK' \
            --header 'Authorization: Bearer ${{ env.TOKEN }}' \
            --data-raw '{
              "ExecutionEnvironment": "Dex",
              "ProjectName": "Atlas001",
              "Events": ["3a134744-5cb3-bc21-1584-01bdb9ffff27"],
              "ImportResult": true,
              "Creator": "MyClientX"
            }'
